flowchart TB

AuthService[AuthService]
TokenService[TokenService - JWT]
RBAC[RBACService]
Tenant[TenantResolver]

AuthService --> TokenService
AuthService --> RBAC
AuthService --> Tenant

Tenant --> DB[(Database)]
RBAC --> DB
AuthService --> DB

%% STYLES
classDef core fill:#BBDEFB,stroke:#0D47A1,stroke-width:2px;
classDef security fill:#FFCDD2,stroke:#B71C1C,stroke-width:2px;
classDef db fill:#E1BEE7,stroke:#4A148C,stroke-width:2px;

class AuthService,TokenService,RBAC,Tenant core;
class DB db;