flowchart TB

EventService[EventService - Orchestrator]
Command[EventCommandService]
Query[EventQueryService]

Strategy[EventTypeStrategy Interface]

Webinar[WebinarStrategy]
Concert[ConcertStrategy]
Competition[CompetitionStrategy]

EventService --> Command
EventService --> Query
EventService --> Strategy

Strategy --> Webinar
Strategy --> Concert
Strategy --> Competition

Command --> DB[(Database)]
Query --> DB

%% STYLES
classDef core fill:#BBDEFB,stroke:#0D47A1,stroke-width:2px;
classDef strategy fill:#C8E6C9,stroke:#1B5E20,stroke-width:2px;
classDef db fill:#E1BEE7,stroke:#4A148C,stroke-width:2px;

class EventService,Command,Query core;
class Strategy,Webinar,Concert,Competition strategy;
class DB db;